[project]
name = "cmdr-data-voice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx-audio>=0.3",
    "soundfile>=0.13.1",
]

[tool.uv]
prerelease = "allow"
